name: data-processor
services:
  postgres-local:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: data_db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5433:5432"
    networks:
      - data-processor

networks:
  data-processor:
    driver: bridge
